
DROP TABLE IF EXISTS W_ERROR_LOG;
DROP TABLE IF EXISTS W_JOB_CHANGE_DATA;


-- create tables…

/*********************************
    W_JOB_CHANGE_DATA
**********************************/  
CREATE TABLE W_JOB_CHANGE_DATA
(
	CHANGE_ID 			INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	CONTRACT_DATE 		CHAR(10), 
	SALES_AGENT_ID 		INTEGER, 
	SALES_CLASS_ID 		INTEGER, 
	LOCATION_ID 		INTEGER, 
	CUST_ID_ORDERED_BY 	INTEGER, 
	DATE_PROMISED 		CHAR(10), 
	DATE_SHIP_BY 		CHAR(10), 
	NUMBER_OF_SUBJOBS 	INTEGER, 
	UNIT_PRICE 			DECIMAL(5,2), 
	QUANTITY_ORDERED 	INTEGER, 
	QUOTE_QTY 			INTEGER, 
	LEAD_ID 			INTEGER
);

/*********************************
    W_ERROR_LOG
**********************************/ 
CREATE TABLE W_ERROR_LOG
(
	Log_Id		INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Change_Id	INTEGER,
	Job_Id		INTEGER,
	Note		VARCHAR(200),
    CONSTRAINT W_ERROR_LOG_CHANGE_ID_FK FOREIGN KEY (CHANGE_ID) REFERENCES W_JOB_CHANGE_DATA (CHANGE_ID)
);